version: '3'

services:
  db:
    build:
      context: docker/mysqld
      dockerfile: Dockerfile
    container_name: fc2blog-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: dev_fc2blog
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/mysqld/data:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: docker/apache
      dockerfile: Dockerfile
    container_name: fc2blog-apache
    environment:
      FC2_APP_DEBUG: 1
      FC2_SQL_DEBUG: 1
      FC2_CONFIG_FROM_ENV: 1
      FC2_ENABLE_UNIT_TEST_ENDPOINT: 1
      FC2_STRICT_ERROR_REPORT: 1
      FC2_ERROR_LOG_PATH: "php://stderr"
      FC2_APP_LOG_PATH: "php://stderr"
      FC2_LOG_LEVEL: 100
      FC2_ERROR_ON_DISPLAY: 1
      FC2_DB_HOST: "db"
      FC2_DB_USER: "docker"
      FC2_DB_PASSWORD: "docker"
      FC2_DB_DATABASE: "dev_fc2blog"
      FC2_DB_CHARSET: "UTF8MB4"
      FC2_DOMAIN: "localhost"
      FC2_HTTP_PORT: "8080"
      FC2_HTTPS_PORT: "8480"
      FC2_DOCUMENT_ROOT_PATH: "/fc2blog/public/"
      DEBUG_FORCE_CAPTCHA_KEY: "1234" # デバッグ用にCAPTCHAの値を固定する
    depends_on:
      - db
    working_dir: "/fc2blog"
    volumes:
      - .:/fc2blog
    ports:
      - 8080:80
      - 8480:443
