name: Test All

on:
  push:
    branches:
      - issue103/gh-action-e2e

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: make docker-compose-build

      - name: docker-compose up
        run: docker-compose up -d

      - name: wait and debug output
        run: |
          sleep 10
          docker ps -a
          curl -v http://127.0.0.1:8080

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test

