name: PhpUnit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fc2dev
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
    steps:
      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, gd, gettext, fileinfo, pdo, pdo_mysql, mysqli
      - uses: actions/checkout@v2
      - name: download sample image
        run: cd tests/test_images && ./download_samples.sh
      - name: get composer
        run: |
          curl -sSfL -o composer-setup.php https://getcomposer.org/installer
          php composer-setup.php --filename=composer.phar
          rm composer-setup.php
      - name: composer install
        run: php composer.phar install --no-ansi --no-interaction --no-scripts --no-progress
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          FC2_CONFIG_FROM_ENV: 1
          FC2_APP_DEBUG: 1
          FC2_SQL_DEBUG: 0
          FC2_STRICT_ERROR_REPORT: 1
          FC2_ERROR_LOG_PATH: "php://stderr"
          FC2_APP_LOG_PATH: "php://stderr"
          FC2_LOG_LEVEL: 100
          FC2_ERROR_ON_DISPLAY: 1
          FC2_DB_HOST: 127.0.0.1
          FC2_DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          FC2_DB_USER: docker
          FC2_DB_PASSWORD: docker
          FC2_DB_DATABASE: fc2dev
          FC2_DB_CHARSET: "UTF8MB4"
          FC2_DOMAIN: "localhost"
          FC2_HTTP_PORT: "8080"
          FC2_HTTPS_PORT: "8480"
          DEBUG_FORCE_CAPTCHA_KEY: "1234" # デバッグ用にCAPTCHAの値を固定する
        run: |
          mkdir -p public/uploads/t/e/s/testblog2/file/
          cp -a tests/test_images/1.png public/uploads/t/e/s/testblog2/file/1.png
          cp -a tests/test_images/2.png public/uploads/t/e/s/testblog2/file/2.png
          touch app/temp/installed.lock
          tests/cli_load_fixture.php
          tests/cli_update_template.php testblog2
          php app/vendor/bin/phpunit --stop-on-failure
